# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.2.1"

package:
  name: confluence-markdown-exporter
  version: ${{ version }}

source:
  url: 
    https://pypi.org/packages/source/c/confluence-markdown-exporter/confluence_markdown_exporter-${{
    version }}.tar.gz
  sha256: ee270e5554dee01e466dd6c6d917a8f883a365aed1492af139efb3469267cb9a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - atlassian-python-api
    - jmespath
    - lxml >=6.0.2
    - markdownify
    - pydantic-settings
    - python-dateutil
    - pyyaml
    - questionary
    - rich
    - tabulate

tests:
  - python:
      imports:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/Spenhouet/confluence-markdown-exporter
  license: MIT
  license_file: LICENSE
  summary: A tool to export Confluence pages to Markdown
  description: "The confluence-markdown-exporter exports Confluence pages in Markdown
    format. \nThis exporter helps in migrating content from Confluence to platforms
    that support Markdown. \ne.g. Obsidian, Gollum, Azure DevOps (ADO), Foam, Dendron
    and more.\n"
  repository: https://github.com/Spenhouet/confluence-markdown-exporter
  documentation: https://spenhouet.github.io/confluence-markdown-exporter/
extra:
  recipe-maintainers:
    - rxm7706
